# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.trabajo import Trabajo  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, trabajos: List[Trabajo]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param trabajos: The trabajos of this InlineResponse200.  # noqa: E501
        :type trabajos: List[Trabajo]
        """
        self.swagger_types = {
            'trabajos': List[Trabajo]
        }

        self.attribute_map = {
            'trabajos': 'trabajos'
        }
        self._trabajos = trabajos

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def trabajos(self) -> List[Trabajo]:
        """Gets the trabajos of this InlineResponse200.

        array de trabajos  # noqa: E501

        :return: The trabajos of this InlineResponse200.
        :rtype: List[Trabajo]
        """
        return self._trabajos

    @trabajos.setter
    def trabajos(self, trabajos: List[Trabajo]):
        """Sets the trabajos of this InlineResponse200.

        array de trabajos  # noqa: E501

        :param trabajos: The trabajos of this InlineResponse200.
        :type trabajos: List[Trabajo]
        """

        self._trabajos = trabajos
