# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.trabajo_links_trabajos import TrabajoLinksTrabajos  # noqa: F401,E501
from swagger_server import util


class TrabajoLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, trabajos: TrabajoLinksTrabajos=None, _self: TrabajoLinksTrabajos=None):  # noqa: E501
        """TrabajoLinks - a model defined in Swagger

        :param trabajos: The trabajos of this TrabajoLinks.  # noqa: E501
        :type trabajos: TrabajoLinksTrabajos
        :param _self: The _self of this TrabajoLinks.  # noqa: E501
        :type _self: TrabajoLinksTrabajos
        """
        self.swagger_types = {
            'trabajos': TrabajoLinksTrabajos,
            '_self': TrabajoLinksTrabajos
        }

        self.attribute_map = {
            'trabajos': 'trabajos',
            '_self': 'self'
        }
        self._trabajos = trabajos
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'TrabajoLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trabajo_links of this TrabajoLinks.  # noqa: E501
        :rtype: TrabajoLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def trabajos(self) -> TrabajoLinksTrabajos:
        """Gets the trabajos of this TrabajoLinks.


        :return: The trabajos of this TrabajoLinks.
        :rtype: TrabajoLinksTrabajos
        """
        return self._trabajos

    @trabajos.setter
    def trabajos(self, trabajos: TrabajoLinksTrabajos):
        """Sets the trabajos of this TrabajoLinks.


        :param trabajos: The trabajos of this TrabajoLinks.
        :type trabajos: TrabajoLinksTrabajos
        """

        self._trabajos = trabajos

    @property
    def _self(self) -> TrabajoLinksTrabajos:
        """Gets the _self of this TrabajoLinks.


        :return: The _self of this TrabajoLinks.
        :rtype: TrabajoLinksTrabajos
        """
        return self.__self

    @_self.setter
    def _self(self, _self: TrabajoLinksTrabajos):
        """Sets the _self of this TrabajoLinks.


        :param _self: The _self of this TrabajoLinks.
        :type _self: TrabajoLinksTrabajos
        """

        self.__self = _self
